import { createClient } from '@supabase/supabase-js'
import dotenv from 'dotenv'

dotenv.config({ path: '.env.local' })

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const locations = [
  { slug: 'houses-for-sale-in-chesterfield', h1: 'Houses for Sale in Chesterfield', type: 'sale', location: 'Chesterfield' },
  { slug: 'property-to-rent-in-chesterfield', h1: 'Property to Rent in Chesterfield', type: 'rent', location: 'Chesterfield' },
  { slug: 'flats-to-rent-in-chesterfield', h1: 'Flats to Rent in Chesterfield', type: 'rent', location: 'Chesterfield' },
  { slug: 'houses-for-sale-in-matlock', h1: 'Houses for Sale in Matlock', type: 'sale', location: 'Matlock' },
  { slug: 'property-for-sale-in-derbyshire', h1: 'Property for Sale in Derbyshire', type: 'sale', location: 'Derbyshire' },
  { slug: 'houses-for-sale-in-sheffield', h1: 'Houses for Sale in Sheffield', type: 'sale', location: 'Sheffield' },
  { slug: 'property-for-sale-in-the-peak-district', h1: 'Property for Sale in the Peak District', type: 'sale', location: 'Peak District' },
  { slug: 'estate-agents-in-chesterfield', h1: 'Estate Agents in Chesterfield', type: 'agents', location: 'Chesterfield' },
  { slug: 'new-homes-for-sale-in-chesterfield', h1: 'New Homes for Sale in Chesterfield', type: 'sale', location: 'Chesterfield' },
  { slug: 'houses-for-sale-in-dronfield', h1: 'Houses for Sale in Dronfield', type: 'sale', location: 'Dronfield' },
  { slug: 'houses-for-sale-in-manchester', h1: 'Houses for Sale in Manchester', type: 'sale', location: 'Manchester' },
  { slug: 'flats-to-rent-in-manchester', h1: 'Flats to Rent in Manchester', type: 'rent', location: 'Manchester' },
  { slug: 'houses-for-sale-in-leeds', h1: 'Houses for Sale in Leeds', type: 'sale', location: 'Leeds' },
  { slug: 'property-to-rent-in-leeds', h1: 'Property to Rent in Leeds', type: 'rent', location: 'Leeds' },
  { slug: 'houses-for-sale-in-nottingham', h1: 'Houses for Sale in Nottingham', type: 'sale', location: 'Nottingham' },
  { slug: 'flats-to-rent-in-nottingham', h1: 'Flats to Rent in Nottingham', type: 'rent', location: 'Nottingham' },
  { slug: 'houses-for-sale-in-birmingham', h1: 'Houses for Sale in Birmingham', type: 'sale', location: 'Birmingham' },
  { slug: 'houses-for-sale-in-bristol', h1: 'Houses for Sale in Bristol', type: 'sale', location: 'Bristol' },
  { slug: 'houses-for-sale-in-london', h1: 'Houses for Sale in London', type: 'sale', location: 'London' },
  { slug: 'property-to-rent-in-london', h1: 'Property to Rent in London', type: 'rent', location: 'London' },
]

async function seed() {
  console.log('Seeding location pages...')
  
  for (const loc of locations) {
    // Note: intro_paragraph will be generated by AI or manually updated later as per Fix 15a
    const { error } = await supabase
      .from('location_pages')
      .upsert({
        slug: loc.slug,
        h1: loc.h1,
        meta_title: `${loc.h1} | Nestiq — Find Your Next Home`,
        meta_description: `Browse the latest ${loc.h1.toLowerCase()}. Search with Nestiq — the UK's fastest growing property portal.`,
        updated_at: new Date().toISOString()
      }, { onConflict: 'slug' })
      
    if (error) {
      console.error(`Error seeding location ${loc.slug}:`, error.message)
    } else {
      console.log(`Seeded location: ${loc.slug}`)
    }
  }
  
  console.log('Location page seeding completed.')
}

seed()
